apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: x-hospital-xfe-content
spec:
  microFrontend: x-hospital-xfe
  element: x-hospital-wl-list
  attributes:
    - name: base-path
      value: /x-emplyee-wl/
    - name: api-base
      value: http://localhost:30081/api
    - name: hospital-id
      value: bobulova
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?x-hospital-wl(/.*)?$"
