apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: x-ambulance-xfe-content
spec:
  microFrontend: x-ambulance-xfe
  element: x-ambulance-wl-list
  attributes:
    - name: base-path
      value: /x-ambulance-wl/
    - name: api-base
      value: http://localhost:5002/api
    - name: ambulance-id
      value: bobulova
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?x-ambulance-wl(/.*)?$"
