apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: sempresionus/ambulance-xfe
    newName: sempresionus/ambulance-xfe # {"$imagepolicy":  "wac-hospital:ambulance-xfe:name"}
    newTag: main # {"$imagepolicy": "wac-hospital:ambulance-xfe:tag"}
