apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

labels:
  - pairs:
      app.kubernetes.io/part-of: wac-hospital
      app.kubernetes.io/name: x-ambulance-wl
    includeSelectors: true
    includeTemplates: true

resources:
  - ../../../apps/x-ambulance-xfe


components:
  - ../../../components/version-release
